### ISSUE TITLE
Connection refused (OS Error: Connection refused, errno = 111), address = www.instagram.com, port = 47794

### ISSUE THREAD

**Issue by lucassantosbicalho** [imtheguna/instagram_public_api#1]
I'm not shure if this is a bug, I get this error trying get insta.getProfileData(ig_page), with public pages.

`E/flutter (11913): [ERROR:flutter/lib/ui/ui_dart_state.cc(198)] Unhandled Exception: SocketException: Connection refused (OS Error: Connection refused, errno = 111), address = www.instagram.com, port = 47794`
`E/flutter (11913): #0      _NativeSocket.startConnect (dart:io-patch/socket_patch.dart:682:35)`
`E/flutter (11913): #1      _RawSocket.startConnect (dart:io-patch/socket_patch.dart:1817:26)`
`E/flutter (11913): #2      RawSocket.startConnect (dart:io-patch/socket_patch.dart:27:23)`
`E/flutter (11913): #3      RawSecureSocket.startConnect (dart:io/secure_socket.dart:299:22)`
`E/flutter (11913): #4      SecureSocket.startConnect (dart:io/secure_socket.dart:77:28)`
`E/flutter (11913): #5      _ConnectionTarget.connect (dart:_http/http_impl.dart:2449:26)`
`E/flutter (11913): #6      _HttpClient._getConnection.connect (dart:_http/http_impl.dart:2867:12)`
`E/flutter (11913): #7      _HttpClient._getConnection (dart:_http/http_impl.dart:2872:12)`
`E/flutter (11913): #8      _HttpClient._openUrl (dart:_http/http_impl.dart:2727:12)`
`E/flutter (11913): #9      _HttpClient.openUrl (dart:_http/http_impl.dart:2591:7)`
`E/flutter (11913): #10     IOClient.send (package:http/src/io_client.dart:35:38)`
`E/flutter (11913): #11     BaseClient._sendUnstreamed (package:http/src/base_client.dart:93:38)`
`E/flutter (11913): #12     BaseClient.get (package:http/src/base_client.dart:27:7)`
`E/flutter (11913): #13     get.<anonymous closure> (package:http/http.dart:46:36)`
`E/flutter (11913): #14     _withClient (package:http/http.dart:164:20)`
`E/flutter (11913): #15     get (package:http/http.dart:46:5)`
`E/flutter (11913): #16     FlutterInsta.getProfileData (package:instagram_public_api/models/instaApi.dart:130:28)`
`E/flutter (11913): #17     _AddPlacePageState.getIGPageInfo (package:p4e/pages/add_place_page.dart:38:41)`
`E/flutter (11913): #18     _AddPlacePageState.build.<anonymous closure> (package:p4e/pages/add_place_page.dart:89:25)`
`E/flutter (11913): #19     _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:1005:21)`
`E/flutter (11913): #20     GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:198:24)`
`E/flutter (11913): #21     TapGestureRecognizer.handleTapUp (package:flutter/src/gestures/tap.dart:613:11)`
`E/flutter (11913): #22     BaseTapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:298:5)`
`E/flutter (11913): #23     BaseTapGestureRecognizer.handlePrimaryPointer (package:flutter/src/gestures/tap.dart:232:7)`
`E/flutter (11913): #24     PrimaryPointerGestureRecognizer.handleEvent (package:flutter/src/gestures/recognizer.dart:563:9)`
`E/flutter (11913): #25     PointerRouter._dispatch (package:flutter/src/gestures/pointer_router.dart:94:12)`
`E/flutter (11913): #26     PointerRouter._dispatchEventToRoutes.<anonymous closure> (package:flutter/src/gestures/pointer_router.dart:139:9)`
`E/flutter (11913): #27     _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:614:13)`
`E/flutter (11913): #28     PointerRouter._dispatchEventToRoutes (package:flutter/src/gestures/pointer_router.dart:137:18)`
`E/flutter (11913): #29     PointerRouter.route (package:flutter/src/gestures/pointer_router.dart:123:7)`
`E/flutter (11913): #30     GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:445:19)`
`E/flutter (11913): #31     GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:425:22)`
`E/flutter (11913): #32     RendererBinding.dispatchEvent (package:flutter/src/rendering/binding.dart:329:11)`
`E/flutter (11913): #33     GestureBinding._handlePointerEventImmediately (package:flutter/src/gestures/binding.dart:380:7)`
`E/flutter (11913): #34     GestureBinding.handlePointerEvent (package:flutter/src/gestures/binding.dart:344:5)`
`E/flutter (11913): #35     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:302:7)`
`E/flutter (11913): #36     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:285:7)`
`E/flutter (11913): #37     _rootRunUnary (dart:async/zone.dart:1442:13)`
`E/flutter (11913): #38     _CustomZone.runUnary (dart:async/zone.dart:1335:19)`
`E/flutter (11913): #39     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1244:7)`
`E/flutter (11913): #40     _invoke1 (dart:ui/hooks.dart:170:10)`
`E/flutter (11913): #41     PlatformDispatcher._dispatchPointerDataPacket (dart:ui/platform_dispatcher.dart:331:7)`
`E/flutter (11913): #42     _dispatchPointerDataPacket (dart:ui/hooks.dart:94:31)`
`E/flutter (11913): `

**Comment by imtheguna** [comment]
Thanks for your report, We will check and update you
