### ISSUE TITLE
error

### ISSUE THREAD

**Issue by shahzadkhan1998** [imtheguna/instagram_public_api#4]
E/flutter (14306): [ERROR:flutter/lib/ui/ui_dart_state.cc(198)] Unhandled Exception: Exception: HTML was returned instead of JSON

**Comment by imtheguna** [comment]
Instagram allows a maximum of around 200–300 request hits per hour. After reaching the limit, you’ll start getting the server error.

**Comment by shahzadkhan1998** [comment]
It's give me for first call.
